export const INDIAN_LOCATIONS = [
  "Manali, Himachal Pradesh",
  "Munnar, Kerala",
  "Coorg, Karnataka",
  "Darjeeling, West Bengal",
  "Rishikesh, Uttarakhand",
  "Jaisalmer, Rajasthan",
  "Andaman Islands",
  "Hampi, Karnataka",
  "Udaipur, Rajasthan",
  "Ooty, Tamil Nadu",
  "Goa",
  "Shimla, Himachal Pradesh",
  "Varanasi, Uttar Pradesh",
  "Mysore, Karnataka",
  "Agra, Uttar Pradesh",
  "Jaipur, Rajasthan",
  "Kodaikanal, Tamil Nadu",
  "Alleppey, Kerala",
  "Leh-Ladakh",
  "Jim Corbett, Uttarakhand",
  "Spiti Valley, Himachal Pradesh",
  "Khajuraho, Madhya Pradesh",
  "Kaziranga, Assam",
  "Pushkar, Rajasthan",
  "Mount Abu, Rajasthan",
  "Pondicherry",
  "Wayanad, Kerala",
  "Meghalaya",
  "Kutch, Gujarat",
  "Auli, Uttarakhand",
];

export const homestays = [
  {
    id: "1",
    name: "Mountain Dew Cottage",
    location: "Manali, Himachal Pradesh",
    price: 1200,
    rating: 4.8,
    reviews: 124,
    image: "https://images.unsplash.com/photo-1510798831971-661eb04b3739?w=600&q=80",
    category: "Nature Stay",
    amenities: ["WiFi", "Home Food", "Parking", "Mountain View"],
    description: "A cozy wooden cottage nestled in the Himalayan foothills with breathtaking mountain views and home-cooked meals.",
    distance: "2.3 km from Mall Road",
    host: "Priya Sharma",
    hostImage: "https://i.pravatar.cc/150?img=44",
    bedrooms: 2,
    guests: 4,
    isFeatured: true,
    diningOptions: ["Home Food", "Chef Available"],
  },
  {
    id: "2",
    name: "Beachside Paradise",
    location: "Goa",
    price: 2500,
    rating: 4.9,
    reviews: 89,
    image: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=600&q=80",
    category: "Luxury",
    amenities: ["WiFi", "Pool", "Beach Access", "Breakfast"],
    description: "Wake up to the sound of waves in this luxurious beachside villa with private pool and tropical garden.",
    distance: "50 m from Beach",
    host: "Raj Fernandes",
    hostImage: "https://i.pravatar.cc/150?img=52",
    bedrooms: 3,
    guests: 6,
    isFeatured: true,
    diningOptions: ["Restaurant Nearby", "Chef Available"],
  },
  {
    id: "3",
    name: "Kerala Heritage Home",
    location: "Munnar, Kerala",
    price: 1800,
    rating: 4.7,
    reviews: 67,
    image: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=600&q=80",
    category: "Family Stay",
    amenities: ["WiFi", "Kerala Food", "Garden", "Ayurveda"],
    description: "Experience authentic Kerala culture in this beautifully restored heritage teak wood home surrounded by tea gardens.",
    distance: "1.5 km from Tea Museum",
    host: "Lakshmi Nair",
    hostImage: "https://i.pravatar.cc/150?img=47",
    bedrooms: 2,
    guests: 5,
    isFeatured: true,
    diningOptions: ["Home Food", "Chef Available"],
  },
  {
    id: "4",
    name: "Desert Dunes Camp",
    location: "Jaisalmer, Rajasthan",
    price: 3500,
    rating: 4.9,
    reviews: 156,
    image: "https://images.unsplash.com/photo-1542401886-65d6c61db217?w=600&q=80",
    category: "Luxury",
    amenities: ["Camel Safari", "Cultural Show", "Bonfire", "All Meals"],
    description: "Spend unforgettable nights under a billion stars at our luxury desert camp with authentic Rajasthani hospitality.",
    distance: "15 km from Golden Fort",
    host: "Bhairu Singh",
    hostImage: "https://i.pravatar.cc/150?img=60",
    bedrooms: 1,
    guests: 2,
    isFeatured: false,
    diningOptions: ["All Meals Included"],
  },
  {
    id: "5",
    name: "Coorg Coffee Planter",
    location: "Coorg, Karnataka",
    price: 2200,
    rating: 4.6,
    reviews: 43,
    image: "https://images.unsplash.com/photo-1605640840605-14ac1855827b?w=600&q=80",
    category: "Nature Stay",
    amenities: ["WiFi", "Coffee Tours", "Organic Food", "Trek"],
    description: "Stay on a working coffee plantation and experience the magic of Coorg with plantation walks and organic meals.",
    distance: "3 km from Abbey Falls",
    host: "Suma Ponnappa",
    hostImage: "https://i.pravatar.cc/150?img=31",
    bedrooms: 2,
    guests: 4,
    isFeatured: false,
    diningOptions: ["Home Food", "Restaurant Nearby"],
  },
  {
    id: "6",
    name: "Rishikesh River View",
    location: "Rishikesh, Uttarakhand",
    price: 999,
    rating: 4.5,
    reviews: 98,
    image: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=600&q=80",
    category: "Budget Stay",
    amenities: ["WiFi", "Yoga", "River View", "Vegetarian Food"],
    description: "Budget-friendly spiritual retreat with stunning Ganga views, daily yoga sessions, and meditation classes.",
    distance: "500 m from Laxman Jhula",
    host: "Anand Sharma",
    hostImage: "https://i.pravatar.cc/150?img=68",
    bedrooms: 1,
    guests: 2,
    isFeatured: false,
    diningOptions: ["Home Food"],
  },
  {
    id: "7",
    name: "Darjeeling Tea Bungalow",
    location: "Darjeeling, West Bengal",
    price: 1600,
    rating: 4.7,
    reviews: 72,
    image: "https://images.unsplash.com/photo-1528127269322-539801943592?w=600&q=80",
    category: "Heritage",
    amenities: ["WiFi", "Tea Tasting", "Fireplace", "Home Food"],
    description: "A colonial-era tea bungalow with panoramic views of Kanchenjunga, complete with tea tasting sessions and cozy fireside evenings.",
    distance: "2 km from Tiger Hill",
    host: "Tashi Dorjee",
    hostImage: "https://i.pravatar.cc/150?img=14",
    bedrooms: 3,
    guests: 6,
    isFeatured: true,
    diningOptions: ["Home Food", "Chef Available"],
  },
  {
    id: "8",
    name: "Udaipur Lake Haveli",
    location: "Udaipur, Rajasthan",
    price: 4200,
    rating: 4.9,
    reviews: 201,
    image: "https://images.unsplash.com/photo-1477587458883-47145ed94245?w=600&q=80",
    category: "Luxury",
    amenities: ["WiFi", "Lake View", "Rooftop Dining", "AC", "Heritage Tour"],
    description: "A stunning haveli overlooking Lake Pichola with rooftop dining and spectacular sunset views of the City Palace.",
    distance: "300 m from City Palace",
    host: "Vikram Rathore",
    hostImage: "https://i.pravatar.cc/150?img=33",
    bedrooms: 4,
    guests: 8,
    isFeatured: true,
    diningOptions: ["Restaurant Nearby", "Chef Available", "Rooftop Dining"],
  },
  {
    id: "9",
    name: "Ooty Rose Garden Cottage",
    location: "Ooty, Tamil Nadu",
    price: 1400,
    rating: 4.5,
    reviews: 55,
    image: "https://images.unsplash.com/photo-1505015390928-f9e55218544f?w=600&q=80",
    category: "Family Stay",
    amenities: ["WiFi", "Garden", "Home Food", "Bonfire"],
    description: "A charming colonial cottage surrounded by rose gardens and eucalyptus trees in the Nilgiri hills.",
    distance: "1 km from Botanical Garden",
    host: "Meera Krishnan",
    hostImage: "https://i.pravatar.cc/150?img=23",
    bedrooms: 2,
    guests: 5,
    isFeatured: false,
    diningOptions: ["Home Food"],
  },
  {
    id: "10",
    name: "Pondicherry French Villa",
    location: "Pondicherry",
    price: 2800,
    rating: 4.8,
    reviews: 93,
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&q=80",
    category: "Luxury",
    amenities: ["WiFi", "AC", "Breakfast", "Cycling", "Beach Nearby"],
    description: "A beautifully restored French colonial villa in the White Town area, steps from the Promenade and cafes.",
    distance: "200 m from Promenade Beach",
    host: "Anita Bose",
    hostImage: "https://i.pravatar.cc/150?img=41",
    bedrooms: 3,
    guests: 6,
    isFeatured: false,
    diningOptions: ["Restaurant Nearby", "Chef Available"],
  },
  {
    id: "11",
    name: "Wayanad Treehouse",
    location: "Wayanad, Kerala",
    price: 3200,
    rating: 4.8,
    reviews: 78,
    image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=600&q=80",
    category: "Nature Stay",
    amenities: ["Treehouse", "Wildlife", "Organic Food", "Trek"],
    description: "Sleep among the treetops in this unique eco-treehouse deep in the Wayanad forests with wildlife sightings.",
    distance: "5 km from Edakkal Caves",
    host: "Suresh Menon",
    hostImage: "https://i.pravatar.cc/150?img=56",
    bedrooms: 1,
    guests: 2,
    isFeatured: false,
    diningOptions: ["Home Food"],
  },
  {
    id: "12",
    name: "Shimla Colonial Retreat",
    location: "Shimla, Himachal Pradesh",
    price: 1800,
    rating: 4.6,
    reviews: 64,
    image: "https://images.unsplash.com/photo-1534378572025-2db6b7b53f3e?w=600&q=80",
    category: "Heritage",
    amenities: ["WiFi", "Fireplace", "Home Food", "Valley View"],
    description: "A grand British-era bungalow on the ridge with original woodwork, roaring fireplace, and valley views.",
    distance: "1 km from The Ridge",
    host: "Devika Thakur",
    hostImage: "https://i.pravatar.cc/150?img=20",
    bedrooms: 3,
    guests: 6,
    isFeatured: false,
    diningOptions: ["Home Food", "Restaurant Nearby"],
  },
];

export const attractions = [
  {
    id: "1",
    name: "Rohtang Pass",
    location: "Manali",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80",
    rating: 4.8,
    entryFee: 0,
    bestTime: "May - October",
    distance: "51 km",
    description: "Stunning high-altitude pass with snow even in summer, offering panoramic Himalayan views.",
    category: "Adventure",
  },
  {
    id: "2",
    name: "Dudhsagar Falls",
    location: "Goa",
    image: "https://images.unsplash.com/photo-1518509562904-e7ef99cdcc86?w=600&q=80",
    rating: 4.7,
    entryFee: 100,
    bestTime: "October - March",
    distance: "60 km",
    description: "Magnificent four-tiered waterfall that looks like a river of milk cascading down the mountains.",
    category: "Nature",
  },
  {
    id: "3",
    name: "Hampi Ruins",
    location: "Hampi, Karnataka",
    image: "https://images.unsplash.com/photo-1566552881560-0be862a7c445?w=600&q=80",
    rating: 4.9,
    entryFee: 600,
    bestTime: "October - February",
    distance: "0 km",
    description: "UNESCO World Heritage site with stunning ruins of the Vijayanagara Empire spanning over 4,000 acres.",
    category: "Heritage",
  },
  {
    id: "4",
    name: "Alleppey Backwaters",
    location: "Alleppey, Kerala",
    image: "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=600&q=80",
    rating: 4.8,
    entryFee: 0,
    bestTime: "November - February",
    distance: "5 km",
    description: "Serene network of lagoons, lakes, and canals lined with coconut palms — best explored by houseboat.",
    category: "Nature",
  },
  {
    id: "5",
    name: "Taj Mahal",
    location: "Agra, Uttar Pradesh",
    image: "https://images.unsplash.com/photo-1564507592333-c60657eea523?w=600&q=80",
    rating: 4.9,
    entryFee: 50,
    bestTime: "October - March",
    distance: "0 km",
    description: "The iconic symbol of love — a white marble mausoleum and one of the Seven Wonders of the World.",
    category: "Heritage",
  },
  {
    id: "6",
    name: "Valley of Flowers",
    location: "Uttarakhand",
    image: "https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=600&q=80",
    rating: 4.7,
    entryFee: 150,
    bestTime: "July - September",
    distance: "17 km trek",
    description: "A UNESCO World Heritage site bursting with alpine flowers, rare herbs, and stunning meadows at 3,600m altitude.",
    category: "Nature",
  },
  {
    id: "7",
    name: "Jaipur City Palace",
    location: "Jaipur, Rajasthan",
    image: "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=600&q=80",
    rating: 4.8,
    entryFee: 500,
    bestTime: "October - March",
    distance: "0 km",
    description: "A magnificent blend of Rajput and Mughal architecture housing museums, courtyards, and the famous Peacock Gate.",
    category: "Heritage",
  },
  {
    id: "8",
    name: "Living Root Bridges",
    location: "Meghalaya",
    image: "https://images.unsplash.com/photo-1506461883276-594a12b11cf3?w=600&q=80",
    rating: 4.9,
    entryFee: 0,
    bestTime: "October - May",
    distance: "3 km trek",
    description: "Ancient living bridges grown from rubber tree roots by the Khasi people — a marvel of bio-engineering.",
    category: "Adventure",
  },
  {
    id: "9",
    name: "Rann of Kutch",
    location: "Kutch, Gujarat",
    image: "https://images.unsplash.com/photo-1482192505345-5655af888cc4?w=600&q=80",
    rating: 4.7,
    entryFee: 100,
    bestTime: "November - February",
    distance: "0 km",
    description: "The white salt desert stretching endlessly under full moonlight — India's most surreal landscape.",
    category: "Nature",
  },
  {
    id: "10",
    name: "Varanasi Ghats",
    location: "Varanasi, Uttar Pradesh",
    image: "https://images.unsplash.com/photo-1561361513-2d000a50f0dc?w=600&q=80",
    rating: 4.8,
    entryFee: 0,
    bestTime: "October - March",
    distance: "0 km",
    description: "The spiritual heart of India — ancient ghats along the Ganga with mesmerizing evening Aarti ceremonies.",
    category: "Spiritual",
  },
];

export const guides = [
  {
    id: "1",
    name: "Arjun Mehta",
    location: "Manali, Himachal Pradesh",
    image: "https://i.pravatar.cc/150?img=11",
    rating: 4.9,
    reviews: 87,
    experience: "8 years",
    languages: ["Hindi", "English", "Punjabi"],
    specialties: ["Trekking", "Photography", "Wildlife"],
    about: "Adventure specialist with 8 years of experience guiding across the Himalayas. Expert in hidden trails and local cuisine.",
    price: 1500,
  },
  {
    id: "2",
    name: "Kavitha Reddy",
    location: "Coorg, Karnataka",
    image: "https://i.pravatar.cc/150?img=35",
    rating: 4.8,
    reviews: 63,
    experience: "5 years",
    languages: ["Kannada", "English", "Tamil"],
    specialties: ["Coffee Plantations", "Bird Watching", "Waterfalls"],
    about: "Local cultural guide and coffee connoisseur who knows every hidden waterfall and birding spot in Coorg.",
    price: 1200,
  },
  {
    id: "3",
    name: "Salim Khan",
    location: "Jaisalmer, Rajasthan",
    image: "https://i.pravatar.cc/150?img=12",
    rating: 4.7,
    reviews: 112,
    experience: "12 years",
    languages: ["Rajasthani", "Hindi", "English", "German"],
    specialties: ["Desert Safari", "Heritage", "Folk Culture"],
    about: "Born in the golden city, Salim brings the magic of Rajasthan to life with stories, songs, and secret spots.",
    price: 1800,
  },
  {
    id: "4",
    name: "Deepa Nambiar",
    location: "Munnar, Kerala",
    image: "https://i.pravatar.cc/150?img=29",
    rating: 4.8,
    reviews: 54,
    experience: "6 years",
    languages: ["Malayalam", "English", "Hindi"],
    specialties: ["Tea Gardens", "Ayurveda", "Backwaters"],
    about: "Born in the tea hills, Deepa offers immersive experiences from plantation walks to Ayurvedic wellness sessions.",
    price: 1400,
  },
  {
    id: "5",
    name: "Tenzing Bhutia",
    location: "Darjeeling, West Bengal",
    image: "https://i.pravatar.cc/150?img=53",
    rating: 4.9,
    reviews: 96,
    experience: "10 years",
    languages: ["Nepali", "Hindi", "English", "Bengali"],
    specialties: ["Himalayan Treks", "Tea Culture", "Monastery Tours"],
    about: "A Sherpa-descended guide who leads treks through the Singalila range and introduces travellers to Tibetan Buddhist culture.",
    price: 2000,
  },
];

export const categories = [
  { id: "1", name: "Family Stay", icon: "🏠", count: 245, color: "bg-blue-50 text-blue-700" },
  { id: "2", name: "Budget Stay", icon: "💰", count: 387, color: "bg-green-50 text-green-700" },
  { id: "3", name: "Luxury", icon: "✨", count: 98, color: "bg-yellow-50 text-yellow-700" },
  { id: "4", name: "Nature Stay", icon: "🌿", count: 312, color: "bg-emerald-50 text-emerald-700" },
  { id: "5", name: "Heritage", icon: "🏯", count: 67, color: "bg-red-50 text-red-700" },
  { id: "6", name: "Beach", icon: "🏖️", count: 145, color: "bg-cyan-50 text-cyan-700" },
];

export const trendingDestinations = [
  { name: "Manali", image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=400&q=80", stays: 45 },
  { name: "Goa", image: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=400&q=80", stays: 78 },
  { name: "Kerala", image: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=400&q=80", stays: 62 },
  { name: "Rajasthan", image: "https://images.unsplash.com/photo-1477587458883-47145ed94245?w=400&q=80", stays: 54 },
  { name: "Darjeeling", image: "https://images.unsplash.com/photo-1548013146-72479768bada?w=400&q=80", stays: 28 },
  { name: "Udaipur", image: "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=400&q=80", stays: 36 },
  { name: "Pondicherry", image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=400&q=80", stays: 41 },
  { name: "Meghalaya", image: "https://images.unsplash.com/photo-1506461883276-594a12b11cf3?w=400&q=80", stays: 19 },
];

export const reviews = [
  {
    id: "1",
    user: "Sneha Patel",
    avatar: "https://i.pravatar.cc/150?img=25",
    rating: 5,
    text: "Absolutely magical experience! The host was incredibly warm and the mountain views were breathtaking. Will definitely return!",
    homestay: "Mountain Dew Cottage",
    date: "January 2025",
  },
  {
    id: "2",
    user: "Rohit Kumar",
    avatar: "https://i.pravatar.cc/150?img=65",
    rating: 5,
    text: "StayVista connected us with the most authentic homestay experience. The local guide was phenomenal — showed us places no tourist usually sees!",
    homestay: "Kerala Heritage Home",
    date: "December 2024",
  },
  {
    id: "3",
    user: "Preethi Iyer",
    avatar: "https://i.pravatar.cc/150?img=10",
    rating: 4,
    text: "Budget-friendly and incredibly cozy. The food was the highlight — better than any restaurant in Rishikesh!",
    homestay: "Rishikesh River View",
    date: "February 2025",
  },
];

export const restaurants = [
  {
    id: "1",
    name: "Mountain Spice Kitchen",
    location: "Manali, Himachal Pradesh",
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600&q=80",
    cuisine: ["Himachali", "North Indian", "Tibetan"],
    rating: 4.7,
    reviews: 214,
    priceRange: "₹200 - ₹600",
    distance: "1.2 km",
    isVeg: false,
    specialDish: "Sidu with Ghee & Dal",
    openHours: "8 AM - 10 PM",
  },
  {
    id: "2",
    name: "Thalassery Seafood House",
    location: "Goa",
    image: "https://images.unsplash.com/photo-1552566626-52f8b828add9?w=600&q=80",
    cuisine: ["Goan", "Seafood", "Portuguese"],
    rating: 4.8,
    reviews: 342,
    priceRange: "₹300 - ₹900",
    distance: "800 m",
    isVeg: false,
    specialDish: "Goan Fish Curry with Rice",
    openHours: "11 AM - 11 PM",
  },
  {
    id: "3",
    name: "Kerala Banana Leaf",
    location: "Munnar, Kerala",
    image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600&q=80",
    cuisine: ["Kerala", "South Indian"],
    rating: 4.6,
    reviews: 156,
    priceRange: "₹150 - ₹450",
    distance: "2 km",
    isVeg: false,
    specialDish: "Appam with Stew",
    openHours: "7 AM - 9 PM",
  },
  {
    id: "4",
    name: "Desert Moon Rooftop",
    location: "Jaisalmer, Rajasthan",
    image: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600&q=80",
    cuisine: ["Rajasthani", "Mughlai"],
    rating: 4.7,
    reviews: 189,
    priceRange: "₹250 - ₹700",
    distance: "500 m",
    isVeg: false,
    specialDish: "Laal Maas with Bajra Roti",
    openHours: "12 PM - 11 PM",
  },
  {
    id: "5",
    name: "Ganga View Café",
    location: "Rishikesh, Uttarakhand",
    image: "https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?w=600&q=80",
    cuisine: ["Vegetarian", "Health Food", "Israeli"],
    rating: 4.5,
    reviews: 278,
    priceRange: "₹100 - ₹350",
    distance: "300 m",
    isVeg: true,
    specialDish: "Thali with Ganga Views",
    openHours: "6 AM - 9 PM",
  },
  {
    id: "6",
    name: "Windmills Craft Café",
    location: "Pondicherry",
    image: "https://images.unsplash.com/photo-1559339352-11d035aa65de?w=600&q=80",
    cuisine: ["French", "Continental", "South Indian"],
    rating: 4.8,
    reviews: 198,
    priceRange: "₹350 - ₹900",
    distance: "1 km",
    isVeg: false,
    specialDish: "Crêpes with Filter Coffee",
    openHours: "8 AM - 10 PM",
  },
];

export const chefs = [
  {
    id: "1",
    name: "Chef Ramesh Thakur",
    location: "Manali, Himachal Pradesh",
    image: "https://i.pravatar.cc/150?img=57",
    rating: 4.9,
    reviews: 67,
    experience: "15 years",
    specialties: ["Himachali", "North Indian", "Tandoor"],
    about: "Ramesh cooks authentic Himachali dishes using family recipes passed down generations. Known for his Sidu and Babru.",
    pricePerMeal: 500,
    pricePerDay: 1800,
    languages: ["Hindi", "English"],
    available: true,
  },
  {
    id: "2",
    name: "Chef Mariamma Joseph",
    location: "Munnar, Kerala",
    image: "https://i.pravatar.cc/150?img=48",
    rating: 4.8,
    reviews: 82,
    experience: "20 years",
    specialties: ["Kerala", "South Indian", "Seafood"],
    about: "Mariamma is a legendary local cook who turns fresh spices and coconut into unforgettable Kerala feasts on banana leaves.",
    pricePerMeal: 450,
    pricePerDay: 1500,
    languages: ["Malayalam", "English", "Tamil"],
    available: true,
  },
  {
    id: "3",
    name: "Chef Sukhdev Singh",
    location: "Jaisalmer, Rajasthan",
    image: "https://i.pravatar.cc/150?img=15",
    rating: 4.7,
    reviews: 54,
    experience: "12 years",
    specialties: ["Rajasthani", "Mughlai", "Desert Cuisine"],
    about: "Sukhdev creates magical desert dinners under the stars using ancient Rajasthani recipes with organic ingredients.",
    pricePerMeal: 600,
    pricePerDay: 2200,
    languages: ["Hindi", "English", "Rajasthani"],
    available: true,
  },
  {
    id: "4",
    name: "Chef Ananya Das",
    location: "Darjeeling, West Bengal",
    image: "https://i.pravatar.cc/150?img=32",
    rating: 4.8,
    reviews: 41,
    experience: "8 years",
    specialties: ["Bengali", "Tibetan", "Momos", "Thukpa"],
    about: "Ananya blends Bengali and Tibetan flavours to create unique mountain comfort food. Her momos are legendary in Darjeeling.",
    pricePerMeal: 400,
    pricePerDay: 1400,
    languages: ["Bengali", "Nepali", "Hindi", "English"],
    available: true,
  },
  {
    id: "5",
    name: "Chef Marco D'Souza",
    location: "Goa",
    image: "https://i.pravatar.cc/150?img=59",
    rating: 4.9,
    reviews: 103,
    experience: "18 years",
    specialties: ["Goan", "Portuguese", "Seafood", "Fusion"],
    about: "Marco brings Goan-Portuguese culinary magic right to your homestay. His Prawn Balchão and Bebinca are award-winning.",
    pricePerMeal: 700,
    pricePerDay: 2500,
    languages: ["Konkani", "English", "Hindi", "Portuguese"],
    available: true,
  },
];
